version: 2
updates:
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - "npm"
      - "dependencies"
      - "need-review"
      - "frontend"
  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - "npm"
      - "dependencies"
      - "need-review"
      - "backend"
  - package-ecosystem: npm
    directory: "/e2e"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    labels:
      - "npm"
      - "dependencies"
      - "need-review"
      - "e2e"
